MYSQL_USERNAME: root
MYSQL_PASSWORD: 1104540868

spring:
  application:
    name: funkytools

  datasource:
    url: jdbc:mysql://localhost:3306/funkytools
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_GITHUB_REDIRECT_URI}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

